version: "3.8"

services:
  #################################
  # RabbitMQ: AMQP
  #################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  #################################
  # Account: The Account microservice
  #################################
  account:
    image: ngkangting/account:1.0
    build: ./account
    restart: always
    ports:
      - "6000:6000"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/account

  #################################
  # Verification: The Verification microservice
  #################################
  verification:
    image: ngkangting/verification:1.0
    build: ./verification
    restart: always
    ports:
      - "6001:6001"
    environment:
      accountURL: http://account:6000/account/
      missionURL: http://mission:6300/mission/
      rewardURL: http://reward:6303/reward/

  #################################
  # Notification: The Notification microservice
  #################################
  notification:
    image: ngkangting/notification:1.0
    build: ./notification
    restart: always
    ports:
      - "6002:6002"

  #################################
  # Redemption: The Redemption microservice
  #################################
  broadcast:
    image: scaryprix/broadcast:1.0
    build: ./broadcast
    ports:
      - "6102:6102"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/broadcast
      accountURL: http://account:6000/account/
      verificationURL: http://verification:6001/verification/
      loyaltyURL: http://loyalty:6301/loyalty/



  #################################
  # Mission: The Mission microservice
  #################################
  mission:
    image: ngkangting/mission:1.0
    build: ./mission
    restart: always
    ports:
      - "6300:6300"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/mission

  #################################
  # Loyalty: The Loyalty microservice
  #################################
  loyalty:
    image: ngkangting/loyalty:1.0
    build: ./loyalty
    restart: always
    ports:
      - "6301:6301"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/loyalty
      verificationURL: http://verification:6001/verification/

  #################################
  # Challenge: The Challenge microservice
  #################################
  challenge:
    image: ngkangting/challenge:1.0
    build: ./challenge
    ports:
      - "6302:6302"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/challenge
      verificationURL: http://verification:6001/verification/
      loyaltyURL: http://loyalty:6301/loyalty/

  #################################
  # Reward: The Reward microservice
  #################################
  reward:
    image: ngkangting/reward:1.0
    build: ./reward
    restart: always
    ports:
      - "6303:6303"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/reward

  #################################
  # Redemption: The Redemption microservice
  #################################
  redemption:
    image: ngkangting/redemption:1.0
    build: ./redemption
    ports:
      - "6304:6304"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/redemption
      verificationURL: http://verification:6001/verification/
      loyaltyURL: http://loyalty:6301/loyalty/


