version: "3.8"

services:
  #################################
  # Notification: The Notification microservice
  #################################
  book:
    image: ESDeezney/notification:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/notification
