version: "3.8"

services:
  #################################
  # Mission: The Mission microservice
  #################################
  book:
    image: ngkangting/mission:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/mission
